server:
  port: 1030
eureka:
  client:
    serviceUrl: #指向Eureka服务端地址
      defaultZone: http://localhost:1010/eureka/
    registry-fetch-interval-seconds: 2 #服务发现的间隔时间
  instance:
    prefer-ip-address: true #开启用IP注册
    instance-id: hrm-config:1030 #自定义实例ID

spring:
  application:
    name: hrm-config #服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xxx/hrm-config.git  #配置远程仓库地址，去仓库中复制
          username: root	#仓库是私有的需要账号
          password: 123456