server:
  port: 1040
eureka:
  client:
    serviceUrl: #指向Eureka服务端地址
      defaultZone: http://localhost:1010/eureka/
    registry-fetch-interval-seconds: 2 #服务发现的间隔时间
  instance:
    prefer-ip-address: true #开启用IP注册
    instance-id: hrm-admin:1040 #自定义实例ID

spring:
  application:
    name: hrm-admin #服务名